In [1]:
import numpy as np
np.__version__


'2.3.3'

In [97]:
x = np.array([1, 2, 3], dtype=np.float32)
y = np.asarray([1., 2., 3.])

print(f"Тип данных в массиве x -> {x.dtype}")
print(f"Тип данных в массиве y -> {y.dtype}")

Тип данных в массиве x -> float32
Тип данных в массиве y -> float64


In [2]:
x = np.array([1, 2, 3], dtype=np.float32)
y = np.array([[1, 2, 3]], dtype=np.float32)
z = np.array([[1], [2], [3]], dtype=np.float32)

print("Массив x:")
print(x)
print(x.shape, end="\n\n")

print("Массив y:")
print(y)
print(y.shape, end="\n\n")

print("Массив z:")
print(z)
print(z.shape)

Массив x:
[1. 2. 3.]
(3,)

Массив y:
[[1. 2. 3.]]
(1, 3)

Массив z:
[[1.]
 [2.]
 [3.]]
(3, 1)


In [100]:
x = np.array([1, 2, 3], dtype=np.float32)
x_T = x.T

print("Массив x:")
print(x)
print(x.shape, end="\n\n")

print("Массив x_T:")
print(x_T)
print(x_T.shape)

Массив x:
[1. 2. 3.]
(3,)

Массив x_T:
[1. 2. 3.]
(3,)


In [101]:
result = x @ x

print(result)
print(result.shape)
print(type(result))

14.0
()
<class 'numpy.float32'>


In [5]:
result = y @ y.T

print(result)
print(result.shape)
print(type(result))

[[14.]]
(1, 1)
<class 'numpy.ndarray'>


In [103]:
result = z.T @ z

print(result)
print(result.shape)
print(type(result))

[[14.]]
(1, 1)
<class 'numpy.ndarray'>


In [ ]:
w = np.array([1, 2, 3], dtype=np.float32)
y = np.array([[1, 2, 3]], dtype=np.float32)

# result = y @ w
# result = y.T @ w
# result = w @ y
# result = w.T @ y
# result = w[:, None] @ y

print(result)
print(result.shape)
print(type(result))

[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]
(3, 3)
<class 'numpy.ndarray'>


In [110]:
X = np.array(
    [[1, 2, 3],
     [2, 3, 4],
     [1, 4, 5]],
     dtype=np.float32
)
w = np.array([1, 2, 3], dtype=np.float32)

# result = X @ w
result = w @ X

print(result)
print(result.shape)
print(type(result))

[ 8. 20. 26.]
(3,)
<class 'numpy.ndarray'>


In [2]:
xs = np.array([1, 2, 7, 4, 5, 6, 7], dtype=np.float32)
ys = np.array([7, 6, 5, 2, 3, 2, 1], dtype=np.float32)

In [3]:
# Вариант 1
N = xs.size
s = []
for x, y in zip(xs, ys):
    q = (y-x)**2
    s.append(q)

result = np.sum(s)/N

print(result)

16.571428


In [4]:
# Вариант 2
N = xs.size
s = (ys - xs)**2
result = np.sum(s)/N

print(result)

16.571428


In [5]:
# Вариант 3
N = xs.size
s = ys - xs
result = (s @ s)/N

print(result)

16.571428


In [6]:
xs = np.array([1, 2, 7, 4, 5, 6, 7], dtype=np.float32)
ys = np.array([7, 6, 5, 2, 3, 2, 1], dtype=np.float32)

N = xs.size
result = (ys @ xs)/N

print(result)

13.714286


In [2]:
xs = np.array([5, 2, 7, 4, 5, 6, 7], dtype=np.float32)
errors = np.array([7, 6, 5, 2, 3, 2, 1], dtype=np.float32)

In [8]:
# Вариант 1
r_1 = -2.0 * np.mean(xs * errors)
r_2 = -2.0 * np.mean(errors)
result = np.array([r_1, r_2])

print(result)

[-35.42857   -7.428571]


In [3]:
# Вариант 2
new_xs = np.stack((xs, np.ones_like(xs)))

print(new_xs)
print(new_xs.shape)

[[5. 2. 7. 4. 5. 6. 7.]
 [1. 1. 1. 1. 1. 1. 1.]]
(2, 7)


In [121]:
N = xs.shape[0]
result = -2.0 * (errors @ new_xs / N)   # (2,)

print(result)

[-35.42857   -7.428571]
