In [1]:
import numpy as np
import torch

np.__version__

'2.3.3'

In [ ]:
# Инициализирую параметры линейного слоя.
W = np.random.rand(4, 5).astype(np.float32)      # size(4, 5)
b = np.random.rand(1, 5).astype(np.float32)      # size(1, 5)

# Входные данные.
x_1 = np.random.rand(1, 4).astype(np.float32)    # size(bs, 4)

# Прямой проход по линейному слою.
pred_1 = x_1@W + b                               # size(bs, 5)

print(pred_1, end="\n\n")

l_1 = np.sum(pred_1)

# Обратный проход.
dl_1 = 1
dpred_1 = dl_1 * np.ones_like(pred_1)          # size(bs, 5)

db = np.sum(dpred_1, axis=0, keepdims=True)    # size(1, 4)
dW = x_1.T @ dpred_1                           # size(4, 5)

dx = dpred_1 @ W.T                             # size(bs, 4)

print(dW.T, end="\n\n")
print(db, end="\n\n")
print(dx)

[[1.1358972  0.7627349  1.046854   0.82579935 0.34527972]]

[[0.35274395 0.3800302  0.36311454 0.10127781]
 [0.35274395 0.3800302  0.36311454 0.10127781]
 [0.35274395 0.3800302  0.36311454 0.10127781]
 [0.35274395 0.3800302  0.36311454 0.10127781]
 [0.35274395 0.3800302  0.36311454 0.10127781]]

[[1. 1. 1. 1. 1.]]

[[2.3435082 1.9804966 2.8233962 2.4929693]]


In [ ]:
# Инициализирую параметры линейного слоя.
linear = torch.nn.Linear(4, 5)
linear.weight = torch.nn.Parameter(torch.tensor(W.T))
linear.bias = torch.nn.Parameter(torch.tensor(b, dtype=torch.float32))

# Входные данные.
x_2 = torch.tensor(x_1, dtype=torch.float32, requires_grad=True)

# Прямой проход по линейному слою.
pred_2 = linear(x_2)

print(pred_2.detach().numpy(), end="\n\n")

l = torch.sum(pred_2)

# Обратный проход.
l.backward()

print(linear.weight.grad.numpy(), end="\n\n")
print(linear.bias.grad.numpy(), end="\n\n")
print(x_2.grad.numpy())

[[1.135897  0.7627349 1.0468541 0.8257994 0.3452797]]

[[0.35274395 0.3800302  0.36311454 0.10127781]
 [0.35274395 0.3800302  0.36311454 0.10127781]
 [0.35274395 0.3800302  0.36311454 0.10127781]
 [0.35274395 0.3800302  0.36311454 0.10127781]
 [0.35274395 0.3800302  0.36311454 0.10127781]]

[[1. 1. 1. 1. 1.]]

[[2.3435082 1.9804966 2.8233962 2.4929693]]


### Два линейных слоя подряд.

In [17]:
# Инициализирую параметры первого линейного слоя.
W_1 = np.random.rand(784, 128).astype(np.float32)    # size(784, 128)
b_1 = np.random.rand(1, 128).astype(np.float32)      # size(1, 128)

# Инициализирую параметры второго линейного слоя.
W_2 = np.random.rand(128, 10).astype(np.float32)     # size(128, 10)
b_2 = np.random.rand(1, 10).astype(np.float32)       # size(1, 10)

# Входные данные.
X = np.random.rand(16, 784).astype(np.float32)       # size(bs, 784)

# Прямой проход.
out_1 = X @ W_1 + b_1                                # size(bs, 128)
"""Здесь должна быть функция активации, но её пока что нет.""" 
out = out_1 @ W_2 + b_2                              # size(bs, 10)

# Обратный проход.
d_out = np.ones_like(out)                       # size(bs, 10)

db_2 = np.sum(d_out, axis=0, keepdims=True)     # size(1, 10)
dW_2 = out_1.T @ d_out                          # size(128, 10)

d_out_1 = d_out @ W_2.T                         # size(bs, 128)

db_1 = np.sum(d_out_1, axis=0, keepdims=True)   # size(1, 128)
dW_1 = X.T @ d_out_1                            # size(784, 128)

d_X = d_out_1 @ W_1.T                           # size(bs, 784)

In [18]:
# Инициализирую параметры первого линейного слоя.
linear_1 = torch.nn.Linear(784, 128)
linear_1.weight = torch.nn.Parameter(torch.tensor(W_1.T))
linear_1.bias = torch.nn.Parameter(torch.tensor(b_1, dtype=torch.float32))

# Инициализирую параметры первого линейного слоя.
linear_2 = torch.nn.Linear(128, 10)
linear_2.weight = torch.nn.Parameter(torch.tensor(W_2.T))
linear_2.bias = torch.nn.Parameter(torch.tensor(b_2, dtype=torch.float32))

# Входные данные.
X = torch.tensor(X, dtype=torch.float32, requires_grad=True)

# Прямой проход по линейному слою.
out_1 = linear_1(X)
"""Здесь должна быть функция активации, но её пока что нет."""
out = linear_2(out_1)

l = torch.sum(out)

# Обратный проход.
l.backward()
